### ISSUE TITLE
Suggestion: Navigation

### ISSUE THREAD

**Issue by 22Ti** [exelix11/SwitchThemeInjector#41]
I'm using your NX Theme Installer. I find it hard to navigate through pages. Lets say there are 7 pages and I need to go to page 3. I have to push down button so many times. Can you please make L button (previous page) and R button (next page) ?

Another note is when i view some theme (lets say it's in page 3) and press back, it jumps back to page 1 instead of staying at previous page and previous item

**Comment by exelix11** [comment]
Sounds reasonable, especially since i increased the number of elements per page with 2.0, will add support to move between pages with L and R.

> Another note is when i view some theme (lets say it's in page 3) and press back, it jumps back to page 1 instead of staying at previous page and previous item

Never encountered this bug, what do you mean with view and then press back ? If you mean previewing you just have to let go of the L button to close the preview, the B button will take you to the previous folder

**Comment by exelix11** [comment]
Ok i think i get what you mean, after installing a theme the cursor will be moved back to the start of the page, never noticed it cause i usually test one theme at a time.
Both issues are fixed now, if there's nothing else i can close this issue

**Comment by 22Ti** [comment]
Thank you for LR button it works great! The second issue is still happening though. What I mean is if I have folder a,b,c and so on. Lets say I'm viewing files in folder "j" now then i hit b button (back). Now the cursor is set back to folder "a" instead of folder "j" (and i have to go through several pages in order to view "k" folder)

**Comment by exelix11** [comment]
oh got it now, shouldn't be hard to fix. Will close the issue once it's done

**Comment by exelix11** [comment]
Added with 19ae22d493d58bd24794a146fd2c10a5f930dc27, will be in the next release

**Comment by 22Ti** [comment]
Thanks!
